---
all:
  children:
    post_cluster:
       hosts:
         host1:
           ansible_host: "192.168.56.205"
           ansible_private_key_file: ".vagrant/machines/host1/virtualbox/private_key"
         host2:
           ansible_host: "192.168.56.206"
           ansible_private_key_file: ".vagrant/machines/host2/virtualbox/private_key"        
         host3:
           ansible_host: "192.168.56.207"
           ansible_private_key_file: ".vagrant/machines/host3/virtualbox/private_key"
    haproxy:
      hosts:
        host4:
          ansible_host: "192.168.56.208"
          ansible_private_key_file: ".vagrant/machines/haproxy/virtualbox/private_key"
          

...
