- name: yum update
  command: "{{ item }}"
  with_items: 
    - yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    - yum -y install http://mirror.centos.org/centos/7/extras/x86_64/Packages/centos-release-scl-rh-2-3.el7.centos.noarch.rpm
    - yum -y install http://mirror.centos.org/centos/7/extras/x86_64/Packages/centos-release-scl-2-3.el7.centos.noarch.rpm
    - yum -y install http://mirror.centos.org/centos/7/sclo/x86_64/rh/Packages/l/llvm-toolset-7-clang-4.0.1-1.el7.x86_64.rpm
    - yum -y install https://rpmfind.net/linux/centos/8-stream/BaseOS/x86_64/os/Packages/libzstd-1.4.4-1.el8.x86_64.rpm
  # register: err
  # until: err.rc == 0
  ignore_errors: true
- name: Install components for building
  command: yum install -y epel-release llvm-toolset-7-clang
  ignore_errors: true
- name: Install postgres
  command: yum install -y postgresql14 postgresql14-server postgresql14-devel 
  ignore_errors: true
- name: Install python
  command: yum -y install python3 python3-devel python3-pip gcc
  ignore_errors: true
- name: simlink psql
  shell: sudo ln -s /usr/pgsql-14/bin/* /usr/sbin/
- name: continue install 
  command: "{{ item }}"
  with_items: 
    - pip3 install --upgrade testresources
    - pip3 install --upgrade setuptools
    - pip3 install psycopg2
  ignore_errors: true
- name: Install patroni
  command: yum install -y etcd python3-etcd patroni patroni-etcd watchdog
- name: create directory
  command: "{{ item }}"
  with_items: 
    - mkdir -p /etc/patroni
